"""AI Resume Summarizer - a minimal Streamlit mini-project.

Paste resume text, click a button, and get a concise 2-3 line
professional summary generated with Hugging Face Inference Providers.
Free to use with a Hugging Face access token.
"""

import os

import streamlit as st
from huggingface_hub import InferenceClient
from huggingface_hub.errors import HfHubHTTPError

# ---------------------------------------------------------------------------
# Token handling
#   - Local:    read from the HUGGINGFACEHUB_API_TOKEN environment variable
#   - Deployed: read from Streamlit secrets (.streamlit/secrets.toml)
# The token is never hardcoded.
# ---------------------------------------------------------------------------
def get_api_token():
    token = os.environ.get("HUGGINGFACEHUB_API_TOKEN")
    if not token:
        try:
            token = st.secrets["HUGGINGFACEHUB_API_TOKEN"]
        except Exception:
            token = None
    return token


# Instruction-following model available through Hugging Face Inference Providers
MODEL = "meta-llama/Llama-3.1-8B-Instruct"
MIN_CHARS = 50
MAX_CHARS = 12000


def summarize_resume(resume_text, api_token):
    """Call Hugging Face Inference Providers and return a short summary string."""
    client = InferenceClient(api_key=api_token)
    prompt = (
        "You are a professional recruiter writing a resume summary.\n"
        "Write exactly 2 to 3 concise, professional sentences in one single "
        "paragraph, and keep the whole summary under 75 words.\n"
        "The summary must highlight the candidate's background, key skills, "
        "experience and projects, and main strengths, in language suitable for "
        "a resume.\n"
        "Start directly with the summary content. Do NOT include any "
        "introductory phrase such as \"Here is a concise summary\" or "
        "\"Summary:\". Do NOT use headings, titles, labels, bullet points, "
        "numbered lists, or line breaks. Do NOT add any explanation or comment "
        "before or after the summary. Output only the summary paragraph itself."
        "\n\nRESUME:\n" + resume_text
    )
    completion = client.chat_completion(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=200,
        temperature=0.3,
    )
    return completion.choices[0].message.content.strip()


# ---------------------------------------------------------------------------
# UI
# ---------------------------------------------------------------------------
st.set_page_config(page_title="AI Resume Summarizer", page_icon="📄")

st.title("📄 AI Resume Summarizer")
st.write(
    "Paste your resume text below and get a concise, professional summary "
    "generated by an AI model."
)

resume_text = st.text_area(
    "Resume text",
    height=320,
    placeholder="Paste the full resume text here...",
)

if st.button("Summarize Resume", type="primary"):
    cleaned = resume_text.strip()

    # --- basic input validation ---
    if not cleaned:
        st.warning("Please paste some resume text first.")
    elif len(cleaned) < MIN_CHARS:
        st.warning(
            f"That looks too short. Please provide at least {MIN_CHARS} characters."
        )
    elif len(cleaned) > MAX_CHARS:
        st.warning(
            f"That is too long ({len(cleaned)} characters). "
            f"Please keep it under {MAX_CHARS} characters."
        )
    else:
        api_token = get_api_token()
        if not api_token:
            st.error(
                "No API token found. Set the HUGGINGFACEHUB_API_TOKEN environment "
                "variable locally, or add it to Streamlit secrets when deploying."
            )
        else:
            try:
                with st.spinner("Generating summary..."):
                    summary = summarize_resume(cleaned, api_token)
                st.subheader("Professional Summary")
                st.success(summary)
            except HfHubHTTPError as e:
                st.error(f"Hugging Face API error: {e}")
            except Exception as e:
                st.error(f"Something went wrong: {e}")

st.caption(
    "Mini-project • Built with Streamlit and Hugging Face Inference Providers"
)
